FROM frolvlad/alpine-oraclejdk8
MAINTAINER edalx
COPY config-server-microservice-1.0.jar /home/config-server-microservice-1.0.jar
EXPOSE 8888
CMD ["java","-jar","/home/config-server-microservice-1.0.jar"]
