FROM frolvlad/alpine-oraclejdk8
MAINTAINER edalx
COPY microservicio-instrumentos-1.0.jar /home/microservicio-instrumentos-1.0.jar
EXPOSE 8083
CMD ["java","-jar","/home/microservicio-instrumentos-1.0.jar"]
