FROM frolvlad/alpine-oraclejdk8
MAINTAINER edalx
COPY eureka-server-microservice-1.0.jar /home/eureka-server-microservice-1.0.jar
EXPOSE 8761
CMD ["java","-jar","/home/eureka-server-microservice-1.0.jar"]
